### ISSUE TITLE
KeyValuePair errors during Test-TargetResource if file doesn't exist

### ISSUE THREAD

**Issue by jcwalker** [PlagueHO/FileContentDsc#13]
KeyValuePair will error during Test-TargetResource when the file listed in Path does not exist.  I think it would be more desirable if Test-TargetResource would test if the file exists and if not return $false.  Thoughts?

**Comment by PlagueHO** [comment]
Great point @jcwalker - I totally agree - this should behave like this. I'll try and put some time in this weekend.

**Comment by jcwalker** [comment]
@PlagueHO Awesome!  If you need any help feel free to reach out.

**Comment by PlagueHO** [comment]
@jcwalker - yep - that sounds good. Less code is usually best :grin:

**Comment by jcwalker** [comment]
@PlagueHO  After my last comment I changed the Assert-ParametersValid to check for the parent path of the file being managed.  That way it has the same functionality as before, at least the same idea :)

[Here](https://github.com/PlagueHO/FileContentDsc/compare/dev...jcwalker:issue%2313) is where I'm at currently.  I have the KeyValuePiarFile resource updated just need to do the same to the other 3 resources.  If you see any problems let me know.

**Comment by PlagueHO** [comment]
I've just got one issue (https://github.com/PowerShell/DscResource.Tests/issues/256) to fix over in DSCResource.Tests for the DSC resource kit before I release this to PS Gallery. But I'm hoping to fix that today. Thanks again for this contribution!
